language: python
python: 3.5
install:
  - pip install tox coveralls
script:
  - tox -- --with-coverage
after_success:
  - coveralls
env:
  - TOXENV=py27-scanning
  - TOXENV=py27-noscanning
  - TOXENV=py34-scanning
  - TOXENV=py34-noscanning
  - TOXENV=py35-scanning
  - TOXENV=py35-noscanning
  - TOXENV=pypy-scanning
  - TOXENV=pypy-noscanning
  - TOXENV=pypy3-scanning
  - TOXENV=pypy3-noscanning
  - TOXENV=flake8
  - TOXENV=docs
