language: python
install:
  - pip install tox coveralls
script:
  - tox -- --with-coverage
after_success:
  - coveralls
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=flake8
  - TOXENV=docs
